version: '3'

services:
  docker-app:
    dockerfile: . Dockerfile
    image: brainweb/interview
    ports:
      - 8080:8080
    depends_on:
      - docker-postgres
  docker-postgres:
    image: brainweb/interview-postgres-it
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=brainweb
      - POSTGRES_PASSWORD=brainweb
    ports:
      - 5432:5432